### PR TITLE
Landing page design improvement

### PR DESCRIPTION
**Pull request by AbirSantra**
Hi, @HetviSoni I have completed working on issue #20. 
I have changed the CSS and added a few divs to match the Figma design even better. Also, I noticed that the logo in the Figma design was too large. So I have made it smaller.

Before:
image

After:
image

Figma Design:
image

In addition to this, the font 'Poppins' used in the Figma design was missing from the project. So I have added it from Google Fonts to the project.

Also, I noticed that after the most recent merge, the file names on the imports were incorrectly capitalized which lead to the app breaking. So I have fixed the import names also.

Hope you approve this PR so that I can start working on the next issue which is also assigned to me.
Thank you,
Abir

### CODE REVIEW

**Comment by AbirSantra** [comment]
@HetviSoni I have resolved the merge conflicts after the recent commits. Please approve of this PR so that I can work on the next issue which is #21.
Thank you

**Comment by HetviSoni** [comment]
Hey, you have done good work👍. But I would request you to remove the unnecessary changes where the code is just rewritten with different indentation. Just keep the necessary changes.
Will merge it after that. 👍

**Comment by AbirSantra** [comment]
> Hey, you have done good work👍. But I would request you to remove the unnecessary changes where the code is just rewritten with different indentation. Just keep the necessary changes. Will merge it after that. 👍

Hi, @HetviSoni can you tell me how to do that? Actually, my tab space on VSCode is set to 4 spaces and it formats on save. That is why the indentations were changed. Can you help me with this?

**Comment by HetviSoni** [comment]
Actually, I too am not aware of this. It might be due to some code formatter like prettier. One thing I can suggest is just make a new branch and make required changes in required files only. Do not change other files codes.

**Comment by AbirSantra** [comment]
> Actually, I too am not aware of this. It might be due to some code formatter like prettier. One thing I can suggest is just make a new branch and make required changes in required files only. Do not change other files codes.

Okay then, after I do that, should I create a new pull request? You can close this one then.

**Pull request closed without merging**
