### PR TITLE
Bg fixed : signup / sign in

### PR DESCRIPTION
**Pull request by horizenight**
#41

### CODE REVIEW

**Comment by HetviSoni** [comment]
please follow the last step correctly https://github.com/HetviSoni/code-fraggers#steps

**Comment by horizenight** [comment]
The last step is somewhat confusing ... do I need to merge the feature branch with my master branch and then open a PR ?

**Comment by HetviSoni** [comment]
While creating pull request do remember to add screenshots of your work. Also link your pull request to the issue by Closes #issue-number .

**Comment by horizenight** [comment]
Signup Page Preview:


Screenshot 2022-10-20 164842

Sign in Page Preview:
Screenshot 2022-10-20 164854


Issue : #41  fixed !

**Comment by HetviSoni** [comment]
Closes #issue-number
Please follow the proper format.

**Comment by horizenight** [comment]
This commit closes #41.
Screenshot of changes 

SignIn Page Preview:


Screenshot 2022-10-20 164842

Sign Up Page Preview:
Screenshot 2022-10-20 164854

**Pull request merged**
