### PR TITLE
Favicon and title added

### PR DESCRIPTION
**Pull request by Rohitsuper69**

### CODE REVIEW

**Review by HetviSoni — COMMENTED** [review]
Thank you for your contribution. But I would like you to go through the contribution guidelines once.

**Comment by Rohitsuper69** [comment]
> Thank you for your contribution. But I would like you to go through the contribution guidelines once.

Yeah done I guess I have to put screenshots also

**Comment by HetviSoni** [comment]
https://github.com/HetviSoni/code-fraggers#steps Do read points 3 and 5.

**Comment by Rohitsuper69** [comment]
> https://github.com/HetviSoni/code-fraggers#steps Do read points 3 and 5.

Ok sir understood

**Comment by Savio629** [comment]
@HetviSoni This issue is assigned to me !!
You can check pr #42 (you can also check the time when I had raised the issue)
Also mentioned in the readme that if only the issue has been assign to you,then only you can start working on it(so I was waiting for your approval).

**Comment by HetviSoni** [comment]
> @HetviSoni This issue is assigned to me !! You can check pr #42 (you can also check the time when I had raised the issue) Also mentioned in the readme that if only the issue has been assign to you,then only you can start working on it(so I was waiting for your approval).

Yes thank you and I appreciate that you followed the guidelines☺️

**Pull request closed without merging**
