### PR TITLE
added footer and favicon

### PR DESCRIPTION
**Pull request by M-Rahul1**
can u review it @HetviSoni & add labels.☑️

### CODE REVIEW

**Comment by M-Rahul1** [comment]
CAN YOU REVIEW @HetviSoni

**Comment by HetviSoni** [comment]
Hey actually you dont have any issue assigned to you for this pull request. So I would request you to go through contributing guidelines once.

**Comment by M-Rahul1** [comment]
https://github.com/HetviSoni/code-fraggers/issues/22#issuecomment-1272553250
You told me to look into footer part.
Anyways footer section wasn't added right.

**Comment by M-Rahul1** [comment]
While i was working on it. There were 2 pr pulled. So should i update to latest and send again.

**Comment by HetviSoni** [comment]
ok Np. Can you show the screenshot of your work?

**Comment by M-Rahul1** [comment]
Screenshot 2022-10-14 080422

**Comment by HetviSoni** [comment]
Hey, it seems like it is redundant. And we don't need it as of now.

**Pull request closed without merging**
